### ISSUE TITLE
error running sh make.sh

### ISSUE THREAD

**Issue by hishambutt13** [violetteshev/bottom-up-features#3]
Hi There. I have make a new environment in anaconda and install all the requirements in it.

```
# packages in environment at /home/hisham/anaconda3/envs/py36:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.9.11                py36_0  
cffi                      1.12.3           py36h2e261b9_0    anaconda
cuda90                    1.0                  h6433d27_0    pytorch
cudatoolkit               9.2                           0  
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.13          py36he6710b0_0    anaconda
dbus                      1.13.6               he372182_0    conda-forge
easydict                  1.9                        py_0    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
ffmpeg                    4.1.3                h167e202_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.9                h516909a_0    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
intel-openmp              2019.4                      243  
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
lame                      3.100             h14c3975_1001    conda-forge
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
libclang                  9.0.0                hc9558a2_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
liblapacke                3.8.0                    12_mkl    conda-forge
libllvm9                  9.0.0                hc9558a2_2    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.9.2                h8b12597_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h576950b_1    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.8.4                h516909a_0    conda-forge
libxml2                   2.9.9                hee79883_5    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
matplotlib                3.1.1                    py36_1    conda-forge
matplotlib-base           3.1.1            py36he7580a8_1    conda-forge
mkl                       2019.4                      243  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.0.14           py36ha843d7b_0  
mkl_random                1.1.0            py36hd6b4f25_0  
msgpack-python            0.6.1            py36hfd86e86_1    anaconda
ncurses                   6.1                  he6710b0_1  
nettle                    3.4.1             h1bed415_1002    conda-forge
ninja                     1.9.0            py36hfd86e86_0  
nspr                      4.20              hf484d3e_1000    conda-forge
nss                       3.46                 he751ad9_0    conda-forge
numpy                     1.17.2           py36haad9e8e_0  
numpy-base                1.17.2           py36hde5b4d6_0  
olefile                   0.46                     py36_0  
opencv                    4.1.1            py36ha799480_1    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1d               h7b6447c_2  
pcre                      8.41              hf484d3e_1003    conda-forge
pillow                    6.1.0            py36h34e0f95_0  
pip                       19.2.3                   py36_0  
pixman                    0.38.0            h516909a_1003    conda-forge
protobuf                  3.9.2            py36he1b5a44_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                     py36_0  
pyparsing                 2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py36hcca6a23_4    conda-forge
python                    3.6.9                h265db76_0  
python-dateutil           2.8.0                      py_0    conda-forge
pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
pyyaml                    5.1.2            py36h7b6447c_0    anaconda
qt                        5.9.7                h0c104cb_3    conda-forge
readline                  7.0                  h7b6447c_5  
scipy                     1.3.1            py36h7c811a0_0    anaconda
setuptools                41.2.0                   py36_0  
sip                       4.19.8          py36hf484d3e_1000    conda-forge
six                       1.12.0                   py36_0  
sqlite                    3.29.0               h7b6447c_0  
tensorboardx              1.8                        py_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
torchvision               0.2.1                      py_2    pytorch
tornado                   6.0.3            py36h516909a_0    conda-forge
tqdm                      4.36.1                     py_0    conda-forge
wheel                     0.33.6                   py36_0  
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.8                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                h96e3832_1    anaconda
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

But when i run sh make.sh it gives this error

```
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
skipping 'numpy_nms/cpu_nms.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
make.sh: 26: make.sh: nvcc: not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
  File "/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory
Compiling roi pooling kernels by nvcc...
make.sh: 36: make.sh: nvcc: not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
  File "/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory
Compiling roi align kernels by nvcc...
make.sh: 45: make.sh: nvcc: not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
  File "/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory
Compiling roi crop kernels by nvcc...
make.sh: 54: make.sh: nvcc: not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
  File "/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory
```

I am tried many things to resolve this but it doesn't work for me. can you please help me?

**Comment by violetteshev** [comment]
Hi, do you have cuda 9.0 installed in /usr/local/cuda-9.0/? I see you have cudatoolkit 9.2 package which is not supported.

**Comment by hishamabutt** [comment]
@violetteshev I think i haven't installed cuda in  /usr/local/. Now i have and i think i have run the make file successfully. but now when i run **python extract_features.py --image_dir /Downloads/bottom-up-features/abc.jpg --out_dir features** it gives this error

```
Traceback (most recent call last):
  File "extract_features.py", line 10, in <module>
    from model.faster_rcnn.resnet import resnet
  File "/home/hisham/Downloads/bottom-up-features/lib/model/faster_rcnn/resnet.py", line 6, in <module>
    from model.faster_rcnn.faster_rcnn import _fasterRCNN
  File "/home/hisham/Downloads/bottom-up-features/lib/model/faster_rcnn/faster_rcnn.py", line 10, in <module>
    from model.rpn.rpn import _RPN
  File "/home/hisham/Downloads/bottom-up-features/lib/model/rpn/rpn.py", line 8, in <module>
    from .proposal_layer import _ProposalLayer
  File "/home/hisham/Downloads/bottom-up-features/lib/model/rpn/proposal_layer.py", line 20, in <module>
    from numpy_nms.cpu_nms import cpu_nms
ModuleNotFoundError: No module named 'numpy_nms.cpu_nms'
```

**Comment by hishambutt13** [comment]
@violetteshev i think i haven't installed cuda in /usr/local/. Now i have and i think i have run make file successfully.

```
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
skipping 'numpy_nms/cpu_nms.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
/home/hisham/Downloads/bottom-up-features/lib/model/nms
['/home/hisham/Downloads/bottom-up-features/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmpr6fh0k_v/_nms.c
setting the current directory to '/tmp/tmpr6fh0k_v'
running build_ext
building '_nms' extension
gcc -pthread -B /home/hisham/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/hisham/anaconda3/envs/py36/include/python3.6m -c _nms.c -o ./_nms.o
gcc -pthread -shared -B /home/hisham/anaconda3/envs/py36/compiler_compat -L/home/hisham/anaconda3/envs/py36/lib -Wl,-rpath=/home/hisham/anaconda3/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 ./_nms.o /home/hisham/Downloads/bottom-up-features/lib/model/nms/src/nms_cuda_kernel.cu.o -o ./_nms.so
Compiling roi pooling kernels by nvcc...
/home/hisham/Downloads/bottom-up-features/lib/model/roi_pooling
generating /tmp/tmpj1xj01mq/_roi_pooling.c
setting the current directory to '/tmp/tmpj1xj01mq'
running build_ext
building '_roi_pooling' extension
creating home
creating home/hisham
creating home/hisham/Downloads
creating home/hisham/Downloads/bottom-up-features
creating home/hisham/Downloads/bottom-up-features/lib
creating home/hisham/Downloads/bottom-up-features/lib/model
creating home/hisham/Downloads/bottom-up-features/lib/model/roi_pooling
creating home/hisham/Downloads/bottom-up-features/lib/model/roi_pooling/src
gcc -pthread -B /home/hisham/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/hisham/anaconda3/envs/py36/include/python3.6m -c _roi_pooling.c -o ./_roi_pooling.o
gcc -pthread -B /home/hisham/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/hisham/anaconda3/envs/py36/include/python3.6m -c /home/hisham/Downloads/bottom-up-features/lib/model/roi_pooling/src/roi_pooling.c -o ./home/hisham/Downloads/bottom-up-features/lib/model/roi_pooling/src/roi_pooling.o
gcc -pthread -shared -B /home/hisham/anaconda3/envs/py36/compiler_compat -L/home/hisham/anaconda3/envs/py36/lib -Wl,-rpath=/home/hisham/anaconda3/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 ./_roi_pooling.o ./home/hisham/Downloads/bottom-up-features/lib/model/roi_pooling/src/roi_pooling.o -o ./_roi_pooling.so
Compiling roi align kernels by nvcc...
/home/hisham/Downloads/bottom-up-features/lib/model/roi_align
generating /tmp/tmpl3c9zs2s/_roi_align.c
setting the current directory to '/tmp/tmpl3c9zs2s'
running build_ext
building '_roi_align' extension
creating home
creating home/hisham
creating home/hisham/Downloads
creating home/hisham/Downloads/bottom-up-features
creating home/hisham/Downloads/bottom-up-features/lib
creating home/hisham/Downloads/bottom-up-features/lib/model
creating home/hisham/Downloads/bottom-up-features/lib/model/roi_align
creating home/hisham/Downloads/bottom-up-features/lib/model/roi_align/src
gcc -pthread -B /home/hisham/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/hisham/anaconda3/envs/py36/include/python3.6m -c _roi_align.c -o ./_roi_align.o
gcc -pthread -B /home/hisham/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/hisham/anaconda3/envs/py36/include/python3.6m -c /home/hisham/Downloads/bottom-up-features/lib/model/roi_align/src/roi_align.c -o ./home/hisham/Downloads/bottom-up-features/lib/model/roi_align/src/roi_align.o
gcc -pthread -shared -B /home/hisham/anaconda3/envs/py36/compiler_compat -L/home/hisham/anaconda3/envs/py36/lib -Wl,-rpath=/home/hisham/anaconda3/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 ./_roi_align.o ./home/hisham/Downloads/bottom-up-features/lib/model/roi_align/src/roi_align.o -o ./_roi_align.so
Compiling roi crop kernels by nvcc...
/home/hisham/Downloads/bottom-up-features/lib/model/roi_crop
generating /tmp/tmpowmxh77b/_roi_crop.c
setting the current directory to '/tmp/tmpowmxh77b'
running build_ext
building '_roi_crop' extension
creating home
creating home/hisham
creating home/hisham/Downloads
creating home/hisham/Downloads/bottom-up-features
creating home/hisham/Downloads/bottom-up-features/lib
creating home/hisham/Downloads/bottom-up-features/lib/model
creating home/hisham/Downloads/bottom-up-features/lib/model/roi_crop
creating home/hisham/Downloads/bottom-up-features/lib/model/roi_crop/src
gcc -pthread -B /home/hisham/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/hisham/anaconda3/envs/py36/include/python3.6m -c _roi_crop.c -o ./_roi_crop.o
gcc -pthread -B /home/hisham/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/hisham/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/hisham/anaconda3/envs/py36/include/python3.6m -c /home/hisham/Downloads/bottom-up-features/lib/model/roi_crop/src/roi_crop.c -o ./home/hisham/Downloads/bottom-up-features/lib/model/roi_crop/src/roi_crop.o
gcc -pthread -shared -B /home/hisham/anaconda3/envs/py36/compiler_compat -L/home/hisham/anaconda3/envs/py36/lib -Wl,-rpath=/home/hisham/anaconda3/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 ./_roi_crop.o ./home/hisham/Downloads/bottom-up-features/lib/model/roi_crop/src/roi_crop.o /home/hisham/Downloads/bottom-up-features/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o -o ./_roi_crop.so
```
But Now when i run the command "python extract_features.py --image_dir /Downloads/bottom-up-features/abc.jpg --out_dir features" it gives this error.

```
/home/hisham/Downloads/bottom-up-features/lib/model/utils/config.py:374: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Traceback (most recent call last):
  File "extract_features.py", line 51, in <module>
    assert use_cuda, 'Works only with CUDA' 
AssertionError: Works only with CUDA

```

can you help me with this?

**Comment by violetteshev** [comment]
It means pytorch doesn't see cuda installed. Can you verify that cuda is installed properly by following this [guide](https://docs.nvidia.com/cuda/archive/9.0/cuda-installation-guide-linux/index.html#post-installation-actions)?

**Comment by hishambutt13** [comment]
@violetteshev Thank you so much for your help its working now.
